name: Test Runner

on:
  schedule:
    - cron: "5 8 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        id: run-tests
        env:
          ADAMIK_API_KEY: ${{ secrets.ADAMIK_API_KEY }}
          STARKNET_PRIVATE_KEY: ${{ secrets.STARKNET_PRIVATE_KEY }}
          UNSECURE_LOCAL_SEED: ${{ secrets.UNSECURE_LOCAL_SEED }}
        run: |
          # Run tests and capture output while preserving exit code
          pnpm run test 2>&1 | tee test-output.log
          exit ${PIPESTATUS[0]}  # Use the exit code from pnpm run test, not tee

      - name: Extract balances
        run: |
          # Extract all balance lines and format them
          BALANCES=$(grep -o '\[BALANCE\].*' test-output.log | sort -u)
          echo "BALANCE_INFO<<EOF" >> $GITHUB_ENV
          if [ -n "$BALANCES" ]; then
            echo "$BALANCES" >> $GITHUB_ENV
            # Write to GitHub Actions summary
            echo "### 💰 Balance Information" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "$BALANCES" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "No balance information found" >> $GITHUB_ENV
            # Write to GitHub Actions summary
            echo "### 💰 Balance Information" >> $GITHUB_STEP_SUMMARY
            echo "No balance information found" >> $GITHUB_STEP_SUMMARY
          fi
          echo "EOF" >> $GITHUB_ENV

      - name: Check test results
        run: |
          if [ "${{ steps.run-tests.outcome }}" == "failure" ]; then
            echo "Tests have failed"
            echo "TESTS_FAILED=true" >> $GITHUB_ENV
          else
            echo "All tests passed"
            echo "TESTS_FAILED=false" >> $GITHUB_ENV
          fi

      - name: Send Slack notification
        if: env.TESTS_FAILED == 'true' # Only run this step if tests failed
        uses: 8398a7/action-slack@v3
        with:
          status: "failure" # Always failure since we only notify on failures
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: |
            :rotating_light: *TEST RUNNER WORKFLOW FAILED!* :rotating_light:
            :github: *Repository:* ${{ github.repository }}
            :bust_in_silhouette: *Triggered by:* ${{ github.actor }}
            :github: *Branch:* ${{ github.ref_name }}

            :moneybag: *Balance Information:*
            ```
            ${{ env.BALANCE_INFO }}
            ```

            :link: *View Run:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            :warning: Check the workflow logs for more details :mag_right:
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Fail the workflow if tests failed
      - name: Exit with test status
        if: env.TESTS_FAILED == 'true'
        run: exit 1
